import type { ResourceConfig } from './types';

export const laborMarketResources: ResourceConfig[] = [
  {
    key: 'nitaqat',
    label: 'Nitaqat (Saudization)',
    labelAr: 'نطاقات (السعودة)',
    endpoint: '/v1/labor-market/nitaqat',
    icon: '🇸🇦',
    columns: [
      { key: 'entity_number', label: 'Entity', labelAr: 'رقم المنشأة' },
      { key: 'current_band', label: 'Band', labelAr: 'النطاق' },
      { key: 'saudization_percentage', label: '%', labelAr: 'النسبة' },
      { key: 'total_employees', label: 'Total', labelAr: 'الإجمالي' },
      { key: 'saudi_employees', label: 'Saudis', labelAr: 'سعوديين' },
    ],
  },
  {
    key: 'gosi-subscriptions',
    label: 'GOSI Subscriptions',
    labelAr: 'اشتراكات التأمينات',
    endpoint: '/v1/labor-market/gosi/subscriptions',
    icon: '🏥',
    columns: [
      { key: 'employee.name', label: 'Employee', labelAr: 'الموظف' },
      { key: 'gosi_number', label: 'GOSI #', labelAr: 'رقم الاشتراك' },
      { key: 'subscriber_type', label: 'Type', labelAr: 'النوع' },
      { key: 'total_subscribable_salary', label: 'Salary', labelAr: 'الراتب الخاضع', type: 'currency' },
      { key: 'employee_share', label: 'Employee Share', labelAr: 'حصة الموظف', type: 'currency' },
      { key: 'employer_share', label: 'Employer Share', labelAr: 'حصة صاحب العمل', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'gosi-monthly',
    label: 'GOSI Monthly',
    labelAr: 'إرسالات التأمينات الشهرية',
    endpoint: '/v1/labor-market/gosi/monthly',
    icon: '📅',
    columns: [
      { key: 'year', label: 'Year', labelAr: 'السنة' },
      { key: 'month', label: 'Month', labelAr: 'الشهر' },
      { key: 'total_subscribers', label: 'Subscribers', labelAr: 'المشتركين' },
      { key: 'grand_total', label: 'Total', labelAr: 'الإجمالي', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'wps-files',
    label: 'WPS Files',
    labelAr: 'ملفات حماية الأجور',
    endpoint: '/v1/labor-market/wps',
    icon: '💳',
    columns: [
      { key: 'year', label: 'Year', labelAr: 'السنة' },
      { key: 'month', label: 'Month', labelAr: 'الشهر' },
      { key: 'total_records', label: 'Employees', labelAr: 'الموظفين' },
      { key: 'total_amount', label: 'Amount', labelAr: 'المبلغ', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'qiwa-contracts',
    label: 'Qiwa Contracts',
    labelAr: 'عقود قوى',
    endpoint: '/v1/labor-market/qiwa/contracts',
    icon: '📝',
    columns: [
      { key: 'employee.name', label: 'Employee', labelAr: 'الموظف' },
      { key: 'contract_type', label: 'Type', labelAr: 'نوع العقد' },
      { key: 'job_title_ar', label: 'Title', labelAr: 'المسمى' },
      { key: 'total_salary', label: 'Salary', labelAr: 'الراتب', type: 'currency' },
      { key: 'start_date', label: 'Start', labelAr: 'البداية', type: 'date' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'muqeem-records',
    label: 'Muqeem (Iqama)',
    labelAr: 'المقيم (الإقامات)',
    endpoint: '/v1/labor-market/muqeem',
    icon: '📊',
    columns: [
      { key: 'employee.name', label: 'Employee', labelAr: 'الموظف' },
      { key: 'iqama_number', label: 'Iqama #', labelAr: 'رقم الإقامة' },
      { key: 'nationality', label: 'Nationality', labelAr: 'الجنسية' },
      { key: 'iqama_expiry_date', label: 'Expiry', labelAr: 'الانتهاء', type: 'date' },
      { key: 'occupation_name', label: 'Occupation', labelAr: 'المهنة' },
      { key: 'iqama_status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'work-permits',
    label: 'Work Permits',
    labelAr: 'تأشيرات العمل',
    endpoint: '/v1/labor-market/labor-office/permits',
    icon: '📄',
    columns: [
      { key: 'permit_type', label: 'Type', labelAr: 'النوع' },
      { key: 'occupation_name', label: 'Occupation', labelAr: 'المهنة' },
      { key: 'nationality', label: 'Nationality', labelAr: 'الجنسية' },
      { key: 'monthly_levy', label: 'Levy', labelAr: 'المقابل', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'labor-violations',
    label: 'Labor Violations',
    labelAr: 'مخالفات مكتب العمل',
    endpoint: '/v1/labor-market/labor-office/violations',
    icon: '⚠️',
    columns: [
      { key: 'violation_type', label: 'Type', labelAr: 'النوع' },
      { key: 'severity', label: 'Severity', labelAr: 'الخطورة' },
      { key: 'fine_amount', label: 'Fine', labelAr: 'الغرامة', type: 'currency' },
      { key: 'due_date', label: 'Due', labelAr: 'الموعد', type: 'date' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'mol-levies',
    label: 'MOL Levies',
    labelAr: 'المقابل المالي',
    endpoint: '/v1/labor-market/labor-office/levies',
    icon: '💰',
    columns: [
      { key: 'year', label: 'Year', labelAr: 'السنة' },
      { key: 'month', label: 'Month', labelAr: 'الشهر' },
      { key: 'billable_count', label: 'Workers', labelAr: 'العمالة' },
      { key: 'total_amount', label: 'Amount', labelAr: 'المبلغ', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'hrdf-programs',
    label: 'HRDF Programs',
    labelAr: 'برامج هدف',
    endpoint: '/v1/labor-market/hrdf/programs',
    icon: '🎓',
    columns: [
      { key: 'program_name_ar', label: 'Program', labelAr: 'البرنامج' },
      { key: 'program_type', label: 'Type', labelAr: 'النوع' },
      { key: 'current_beneficiaries', label: 'Beneficiaries', labelAr: 'المستفيدين' },
      { key: 'support_amount_per_month', label: 'Support', labelAr: 'الدعم', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'mudad-submissions',
    label: 'Mudad Compliance',
    labelAr: 'امتثال مدد',
    endpoint: '/v1/labor-market/mudad',
    icon: '✅',
    columns: [
      { key: 'year', label: 'Year', labelAr: 'السنة' },
      { key: 'month', label: 'Month', labelAr: 'الشهر' },
      { key: 'compliance_percentage', label: 'Compliance', labelAr: 'الامتثال %' },
      { key: 'compliance_status', label: 'Band', labelAr: 'التصنيف' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'ajeer-contracts',
    label: 'Ajeer Contracts',
    labelAr: 'عقود أجير',
    endpoint: '/v1/labor-market/ajeer/contracts',
    icon: '🤝',
    columns: [
      { key: 'worker_name', label: 'Worker', labelAr: 'العامل' },
      { key: 'contract_type', label: 'Type', labelAr: 'النوع' },
      { key: 'direction', label: 'Direction', labelAr: 'الاتجاه' },
      { key: 'occupation', label: 'Occupation', labelAr: 'المهنة' },
      { key: 'agreed_amount', label: 'Amount', labelAr: 'المبلغ', type: 'currency' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
  {
    key: 'taqat-postings',
    label: 'Taqat Job Postings',
    labelAr: 'إعلانات طاقات',
    endpoint: '/v1/labor-market/taqat/postings',
    icon: '💼',
    columns: [
      { key: 'job_title_ar', label: 'Title', labelAr: 'المسمى' },
      { key: 'city', label: 'City', labelAr: 'المدينة' },
      { key: 'job_type', label: 'Type', labelAr: 'النوع' },
      { key: 'positions_count', label: 'Positions', labelAr: 'العدد' },
      { key: 'applications_count', label: 'Applications', labelAr: 'المتقدمين' },
      { key: 'status', label: 'Status', labelAr: 'الحالة' },
    ],
  },
];
