import type { ResourceConfig } from './types';
export const platformResources: ResourceConfig[] = [
 {key:'imports',label:'Data Imports',labelAr:'استيراد البيانات',endpoint:'/v1/platform/imports',icon:'⬆️',columns:[{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'format',label:'Format',labelAr:'الصيغة'},{key:'total_rows',label:'Rows',labelAr:'الصفوف'},{key:'success_rows',label:'Success',labelAr:'ناجح'},{key:'failed_rows',label:'Failed',labelAr:'فشل'},{key:'status',label:'Status',labelAr:'الحالة'}]},
 {key:'exports',label:'Data Exports',labelAr:'تصدير البيانات',endpoint:'/v1/platform/exports',icon:'⬇️',columns:[{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'format',label:'Format',labelAr:'الصيغة'},{key:'total_rows',label:'Rows',labelAr:'الصفوف'},{key:'status',label:'Status',labelAr:'الحالة'}]},
 {key:'workflows',label:'Workflow Automation',labelAr:'سير العمل الآلي',endpoint:'/v1/platform/workflows',icon:'🔁',columns:[{key:'name',label:'Name',labelAr:'الاسم'},{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'is_active',label:'Active',labelAr:'مفعل',type:'boolean'}]},
 {key:'approvals',label:'Approvals',labelAr:'الموافقات',endpoint:'/v1/platform/approvals',icon:'✅',columns:[{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'entity_id',label:'Record',labelAr:'السجل'},{key:'status',label:'Status',labelAr:'الحالة'},{key:'comment',label:'Comment',labelAr:'التعليق'}]},
 {key:'integrations',label:'Integrations Hub',labelAr:'مركز التكاملات',endpoint:'/v1/platform/integrations',icon:'🔌',columns:[{key:'name',label:'Name',labelAr:'الاسم'},{key:'provider',label:'Provider',labelAr:'المزود'},{key:'category',label:'Category',labelAr:'التصنيف'},{key:'status',label:'Status',labelAr:'الحالة'}]},
 {key:'webhooks',label:'Webhooks',labelAr:'إشعارات Webhooks',endpoint:'/v1/platform/webhooks',icon:'🪝',columns:[{key:'name',label:'Name',labelAr:'الاسم'},{key:'endpoint',label:'Endpoint',labelAr:'الرابط'},{key:'is_active',label:'Active',labelAr:'مفعل',type:'boolean'}]},
 {key:'scheduled-reports',label:'Scheduled Reports',labelAr:'التقارير المجدولة',endpoint:'/v1/platform/scheduled-reports',icon:'📅',columns:[{key:'name',label:'Name',labelAr:'الاسم'},{key:'report_key',label:'Report',labelAr:'التقرير'},{key:'frequency',label:'Frequency',labelAr:'التكرار'},{key:'is_active',label:'Active',labelAr:'مفعل',type:'boolean'}]},
 {key:'custom-fields',label:'Custom Fields',labelAr:'الحقول المخصصة',endpoint:'/v1/platform/custom-fields',icon:'🧩',columns:[{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'key',label:'Key',labelAr:'المفتاح'},{key:'label',label:'Label',labelAr:'العنوان'},{key:'type',label:'Type',labelAr:'النوع'}]},
 {key:'notification-templates',label:'Notification Templates',labelAr:'قوالب الإشعارات',endpoint:'/v1/platform/notification-templates',icon:'🔔',columns:[{key:'event',label:'Event',labelAr:'الحدث'},{key:'channel',label:'Channel',labelAr:'القناة'},{key:'is_active',label:'Active',labelAr:'مفعل',type:'boolean'}]},
 {key:'audit-logs',label:'Audit Trail',labelAr:'سجل التدقيق',endpoint:'/v1/platform/audit-logs',icon:'🛡️',columns:[{key:'action',label:'Action',labelAr:'الإجراء'},{key:'entity',label:'Entity',labelAr:'الكيان'},{key:'entity_id',label:'Record',labelAr:'السجل'},{key:'user_id',label:'User',labelAr:'المستخدم'}]},
];
