import { options, projectStatus, projectType } from './options'
import type { Resource } from './types'

export const projects: Resource = {
  slug: 'projects',
  title: 'المشاريع',
  subtitle: 'كل التقارير المالية بتقبل فلترة بالمشروع — يعني قوائم مالية لكل مشروع لوحده.',
  endpoint: '/projects',
  create: true,
  edit: true,
  remove: true,
  searchable: true,
  filters: [
    { name: 'status', label: 'الحالة', options: projectStatus },
    { name: 'type', label: 'النوع', options: projectType },
  ],
  columns: [
    { key: 'project_code', label: 'الكود', format: 'code' },
    { key: 'name', label: 'المشروع' },
    { key: 'type', label: 'النوع', format: 'badge' },
    { key: 'client_name', label: 'العميل' },
    { key: 'manager.name', label: 'مدير المشروع' },
    { key: 'contract_value', label: 'قيمة العقد', format: 'money' },
    { key: 'progress_percent', label: 'الإنجاز', format: 'percent' },
    { key: 'status', label: 'الحالة', format: 'badge' },
  ],
  fields: [
    { name: 'project_code', label: 'كود المشروع', required: true, only: 'create' },
    { name: 'name', label: 'اسم المشروع', required: true },
    { name: 'type', label: 'النوع', kind: 'select', options: projectType, required: true, only: 'create' },
    { name: 'client_name', label: 'اسم العميل' },
    { name: 'location', label: 'الموقع' },
    { name: 'budget', label: 'الموازنة', kind: 'number', step: '0.01' },
    { name: 'contract_value', label: 'قيمة العقد', kind: 'number', step: '0.01' },
    { name: 'start_date', label: 'تاريخ البدء', kind: 'date', only: 'create' },
    { name: 'expected_end_date', label: 'النهاية المتوقعة', kind: 'date' },
    { name: 'actual_end_date', label: 'النهاية الفعلية', kind: 'date', only: 'edit' },
    { name: 'project_manager_id', label: 'مدير المشروع', kind: 'ref', ref: 'users' },
    { name: 'status', label: 'الحالة', kind: 'select', options: projectStatus, only: 'edit' },
    {
      name: 'progress_percent',
      label: 'نسبة الإنجاز %',
      kind: 'number',
      min: 0,
      max: 100,
      only: 'edit',
    },
    { name: 'description', label: 'الوصف', kind: 'textarea', span: 2 },
  ],
}

export const contracts: Resource = {
  slug: 'contracts',
  title: 'العقود',
  endpoint: '/contracts',
  create: true,
  edit: true,
  remove: true,
  filters: [
    {
      name: 'status',
      label: 'الحالة',
      options: options({
        draft: 'مسودة',
        active: 'نشط',
        completed: 'مكتمل',
        terminated: 'مفسوخ',
      }),
    },
  ],
  columns: [
    { key: 'contract_number', label: 'رقم العقد', format: 'code' },
    { key: 'party_name', label: 'الطرف الآخر' },
    { key: 'contract_type', label: 'النوع', format: 'badge' },
    { key: 'project.name', label: 'المشروع' },
    { key: 'contract_value', label: 'القيمة', format: 'money' },
    { key: 'retention_percent', label: 'المحتجز', format: 'percent' },
    { key: 'end_date', label: 'النهاية', format: 'date' },
    { key: 'status', label: 'الحالة', format: 'badge' },
  ],
  fields: [
    { name: 'contract_number', label: 'رقم العقد', required: true, only: 'create' },
    { name: 'party_name', label: 'الطرف الآخر', required: true },
    {
      name: 'contract_type',
      label: 'نوع العقد',
      kind: 'select',
      required: true,
      only: 'create',
      options: options({
        main: 'عقد رئيسي',
        subcontract: 'عقد باطن',
        supply: 'توريد',
        consultancy: 'استشارات',
        lease: 'إيجار',
      }),
    },
    { name: 'project_id', label: 'المشروع', kind: 'ref', ref: 'projects', only: 'create' },
    { name: 'contract_value', label: 'قيمة العقد', kind: 'number', step: '0.01', required: true },
    {
      name: 'retention_percent',
      label: 'نسبة المحتجز %',
      kind: 'number',
      step: '0.01',
      min: 0,
      max: 100,
    },
    { name: 'start_date', label: 'تاريخ البدء', kind: 'date', only: 'create' },
    { name: 'end_date', label: 'تاريخ النهاية', kind: 'date' },
    {
      name: 'status',
      label: 'الحالة',
      kind: 'select',
      only: 'edit',
      options: options({
        draft: 'مسودة',
        active: 'نشط',
        completed: 'مكتمل',
        terminated: 'مفسوخ',
      }),
    },
    { name: 'terms', label: 'الشروط', kind: 'textarea', span: 2 },
  ],
}

export const properties: Resource = {
  slug: 'properties',
  title: 'العقارات والوحدات',
  endpoint: '/real-estate/properties',
  create: true,
  edit: true,
  remove: true,
  filters: [
    {
      name: 'status',
      label: 'الحالة',
      options: options({
        available: 'متاح',
        reserved: 'محجوز',
        sold: 'مُباع',
        rented: 'مؤجر',
        under_construction: 'تحت الإنشاء',
      }),
    },
    {
      name: 'property_type',
      label: 'النوع',
      options: options({
        residential: 'سكني',
        commercial: 'تجاري',
        land: 'أرض',
        industrial: 'صناعي',
        mixed_use: 'متعدد الاستخدام',
      }),
    },
  ],
  columns: [
    { key: 'property_code', label: 'الكود', format: 'code' },
    { key: 'name', label: 'العقار' },
    { key: 'property_type', label: 'النوع', format: 'badge' },
    { key: 'project.name', label: 'المشروع' },
    { key: 'unit_number', label: 'رقم الوحدة', format: 'code' },
    { key: 'area_sqm', label: 'المساحة م²', format: 'number' },
    { key: 'price', label: 'السعر', format: 'money' },
    { key: 'status', label: 'الحالة', format: 'badge' },
  ],
  fields: [
    { name: 'property_code', label: 'كود العقار', required: true, only: 'create' },
    { name: 'name', label: 'الاسم', required: true },
    {
      name: 'property_type',
      label: 'النوع',
      kind: 'select',
      required: true,
      only: 'create',
      options: options({
        residential: 'سكني',
        commercial: 'تجاري',
        land: 'أرض',
        industrial: 'صناعي',
        mixed_use: 'متعدد الاستخدام',
      }),
    },
    { name: 'project_id', label: 'المشروع', kind: 'ref', ref: 'projects', only: 'create' },
    { name: 'location', label: 'الموقع', only: 'create' },
    { name: 'unit_number', label: 'رقم الوحدة', only: 'create' },
    { name: 'area_sqm', label: 'المساحة (م²)', kind: 'number', step: '0.01', only: 'create' },
    { name: 'price', label: 'السعر', kind: 'number', step: '0.01', required: true },
    { name: 'bedrooms', label: 'غرف النوم', kind: 'number', only: 'create' },
    { name: 'bathrooms', label: 'دورات المياه', kind: 'number', only: 'create' },
    {
      name: 'status',
      label: 'الحالة',
      kind: 'select',
      only: 'edit',
      options: options({
        available: 'متاح',
        reserved: 'محجوز',
        sold: 'مُباع',
        rented: 'مؤجر',
        under_construction: 'تحت الإنشاء',
      }),
    },
    { name: 'description', label: 'الوصف', kind: 'textarea', span: 2 },
  ],
}

export const qualityInspections: Resource = {
  slug: 'quality-inspections',
  title: 'تفتيشات الجودة',
  endpoint: '/quality/inspections',
  create: true,
  edit: true,
  remove: true,
  filters: [
    {
      name: 'result',
      label: 'النتيجة',
      options: options({
        pending: 'قيد الانتظار',
        passed: 'ناجح',
        failed: 'راسب',
        needs_rework: 'يحتاج إعادة',
      }),
    },
  ],
  columns: [
    { key: 'inspection_code', label: 'الكود', format: 'code' },
    { key: 'subject', label: 'الموضوع' },
    { key: 'project.name', label: 'المشروع' },
    { key: 'inspector.name', label: 'المفتّش' },
    { key: 'inspection_date', label: 'التاريخ', format: 'date' },
    { key: 'result', label: 'النتيجة', format: 'badge' },
  ],
  fields: [
    { name: 'subject', label: 'موضوع التفتيش', required: true },
    { name: 'project_id', label: 'المشروع', kind: 'ref', ref: 'projects', only: 'create' },
    { name: 'inspection_date', label: 'تاريخ التفتيش', kind: 'date', required: true, only: 'create' },
    { name: 'inspector_id', label: 'المفتّش', kind: 'ref', ref: 'users', only: 'create' },
    {
      name: 'result',
      label: 'النتيجة',
      kind: 'select',
      only: 'edit',
      options: options({
        pending: 'قيد الانتظار',
        passed: 'ناجح',
        failed: 'راسب',
        needs_rework: 'يحتاج إعادة',
      }),
    },
    { name: 'findings', label: 'الملاحظات', kind: 'textarea', span: 2 },
    { name: 'corrective_action', label: 'الإجراء التصحيحي', kind: 'textarea', span: 2, only: 'edit' },
  ],
}

export const fixedAssets: Resource = {
  slug: 'fixed-assets',
  title: 'الأصول الثابتة',
  subtitle: 'تشغيل الإهلاك بيضيف قسط سنة واحدة للمجمّع، وبيقف عند القيمة القابلة للإهلاك.',
  endpoint: '/fixed-assets/assets',
  create: true,
  edit: true,
  remove: true,
  filters: [
    {
      name: 'category',
      label: 'التصنيف',
      options: options({
        heavy_equipment: 'معدات ثقيلة',
        vehicle: 'مركبة',
        tool: 'عدة',
        building: 'مبنى',
        furniture: 'أثاث',
        it_equipment: 'أجهزة حاسب',
        other: 'أخرى',
      }),
    },
    {
      name: 'status',
      label: 'الحالة',
      options: options({
        active: 'نشط',
        under_maintenance: 'تحت الصيانة',
        disposed: 'مُستبعد',
        sold: 'مُباع',
      }),
    },
  ],
  columns: [
    { key: 'asset_code', label: 'الكود', format: 'code' },
    { key: 'name', label: 'الأصل' },
    { key: 'category', label: 'التصنيف', format: 'badge' },
    { key: 'project.name', label: 'المشروع' },
    { key: 'purchase_cost', label: 'التكلفة', format: 'money' },
    { key: 'accumulated_depreciation', label: 'مجمّع الإهلاك', format: 'money' },
    { key: 'status', label: 'الحالة', format: 'badge' },
  ],
  fields: [
    { name: 'asset_code', label: 'كود الأصل', required: true, only: 'create' },
    { name: 'name', label: 'اسم الأصل', required: true },
    {
      name: 'category',
      label: 'التصنيف',
      kind: 'select',
      required: true,
      only: 'create',
      options: options({
        heavy_equipment: 'معدات ثقيلة',
        vehicle: 'مركبة',
        tool: 'عدة',
        building: 'مبنى',
        furniture: 'أثاث',
        it_equipment: 'أجهزة حاسب',
        other: 'أخرى',
      }),
    },
    { name: 'project_id', label: 'المشروع', kind: 'ref', ref: 'projects', only: 'create' },
    { name: 'purchase_date', label: 'تاريخ الشراء', kind: 'date', required: true, only: 'create' },
    { name: 'purchase_cost', label: 'تكلفة الشراء', kind: 'number', step: '0.01', required: true, only: 'create' },
    { name: 'useful_life_years', label: 'العمر الإنتاجي (سنة)', kind: 'number', min: 1, max: 100, required: true, only: 'create' },
    { name: 'salvage_value', label: 'القيمة التخريدية', kind: 'number', step: '0.01', only: 'create' },
    {
      name: 'depreciation_method',
      label: 'طريقة الإهلاك',
      kind: 'select',
      required: true,
      only: 'create',
      options: options({ straight_line: 'قسط ثابت', declining_balance: 'رصيد متناقص' }),
    },
    { name: 'location', label: 'الموقع' },
    {
      name: 'status',
      label: 'الحالة',
      kind: 'select',
      only: 'edit',
      options: options({
        active: 'نشط',
        under_maintenance: 'تحت الصيانة',
        disposed: 'مُستبعد',
        sold: 'مُباع',
      }),
    },
  ],
  actions: [
    {
      label: 'تشغيل الإهلاك',
      variant: 'ghost',
      path: (row) => `/fixed-assets/assets/${row.id}/run-depreciation`,
      when: (row) => row.status === 'active',
      confirm: 'هيتضاف قسط إهلاك سنة واحدة لمجمّع الإهلاك. تأكيد؟',
    },
  ],
}
